{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sampleapp.serviceAccountName" . }}
  labels:
{{ include "sampleapp.labels" . | indent 4 }}
{{- end -}}
